name: pheasant_house
description: "A new Flutter project."
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.17.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  typed_data: ^1.3.0  
  mqtt_client: '>=3.2.2 <10.0.0'
  flutter_mqtt: ^1.0.0+5
  file_picker: ^6.1.1
  csv: ^5.1.1

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0
  pdf: ^3.10.8
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.5
  flutter_intl: ^0.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg
  

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
