name: pheasant_house
description: "A new Flutter project."
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  typed_data: ^1.3.0  
  mqtt_client: ^10.2.1
  flutter_mqtt: ^1.0.0+5
  file_picker: ^8.0.3
  csv: ^6.0.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.0.9
  flutter_intl: ^0.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg
  

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
