// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXPCWhMitcbXu7YMKCrIjDnIC0Ovbbos',
    appId: '1:730239248021:web:943c907f78e77603ee1d9c',
    messagingSenderId: '730239248021',
    projectId: 'smartpheasenthouse',
    authDomain: 'smartpheasenthouse.firebaseapp.com',
    databaseURL: 'https://smartpheasenthouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpheasenthouse.appspot.com',
    measurementId: 'G-TCWW9LHED2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRTK8aSQNAF4kS4qBzXfGQ-KNwKWL_bs',
    appId: '1:730239248021:android:80c08d33f415add7ee1d9c',
    messagingSenderId: '730239248021',
    projectId: 'smartpheasenthouse',
    databaseURL: 'https://smartpheasenthouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpheasenthouse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5se8ZeixNdK9TMpA3lcpOnF5T6AGoZW8',
    appId: '1:730239248021:ios:d71c4fdedb285a6fee1d9c',
    messagingSenderId: '730239248021',
    projectId: 'smartpheasenthouse',
    databaseURL: 'https://smartpheasenthouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpheasenthouse.appspot.com',
    iosClientId: '730239248021-p719j9sftl2qs2q7njpnb23467ur1jqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pheasantHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5se8ZeixNdK9TMpA3lcpOnF5T6AGoZW8',
    appId: '1:730239248021:ios:d71c4fdedb285a6fee1d9c',
    messagingSenderId: '730239248021',
    projectId: 'smartpheasenthouse',
    databaseURL: 'https://smartpheasenthouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpheasenthouse.appspot.com',
    iosClientId: '730239248021-p719j9sftl2qs2q7njpnb23467ur1jqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pheasantHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAXPCWhMitcbXu7YMKCrIjDnIC0Ovbbos',
    appId: '1:730239248021:web:039c4a02789cee1dee1d9c',
    messagingSenderId: '730239248021',
    projectId: 'smartpheasenthouse',
    authDomain: 'smartpheasenthouse.firebaseapp.com',
    databaseURL: 'https://smartpheasenthouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpheasenthouse.appspot.com',
    measurementId: 'G-9NEZ4H0NCQ',
  );
}
